/* Generated by Yosys 0.9 (git sha1 1979e0b) */

/* top =  1  */
/* src = "top.v:1" */
module smart_gate_controller(clk_i, reset_i, car_i, pay_ok_i, clear_i, cnt_reset_i, gate_open_o, gate_close_o, L_red_o, L_yellow_o, L_green_o, car_count__o);
  /* src = "top.v:39" */
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  /* src = "top.v:12" */
  output L_green_o;
  /* src = "top.v:10" */
  output L_red_o;
  /* src = "top.v:11" */
  output L_yellow_o;
  /* init = 8'h00 */
  /* src = "top.v:24" */
  reg [7:0] car_count = 8'h00;
  /* src = "top.v:13" */
  output [7:0] car_count__o;
  /* src = "top.v:4" */
  input car_i;
  /* src = "top.v:6" */
  input clear_i;
  /* src = "top.v:2" */
  input clk_i;
  /* src = "top.v:7" */
  input cnt_reset_i;
  /* init = 3'h0 */
  /* src = "top.v:22" */
  reg [2:0] cs = 3'h0;
  /* src = "top.v:9" */
  output gate_close_o;
  /* src = "top.v:8" */
  output gate_open_o;
  /* src = "top.v:23" */
  wire [1:0] next_timer;
  /* src = "top.v:22" */
  wire [2:0] ns;
  /* src = "top.v:5" */
  input pay_ok_i;
  /* src = "top.v:3" */
  input reset_i;
  /* init = 2'h0 */
  /* src = "top.v:23" */
  reg [1:0] timer = 2'h0;
  assign _006_ = ~(timer[0] | timer[1]);
  assign _007_ = ~(cs[0] | cs[1]);
  assign _008_ = ~(cs[2] & _007_);
  assign _009_ = _006_ & ~(_008_);
  assign _010_ = car_count[0] & _009_;
  assign _011_ = ~(car_count[0] | _009_);
  assign _012_ = ~(cnt_reset_i | _011_);
  assign _000_[0] = _012_ & ~(_010_);
  assign _013_ = car_count[1] & _010_;
  assign _014_ = ~(car_count[1] | _010_);
  assign _015_ = ~(cnt_reset_i | _014_);
  assign _000_[1] = _015_ & ~(_013_);
  assign _016_ = car_count[2] & _013_;
  assign _017_ = ~(car_count[2] | _013_);
  assign _018_ = ~(cnt_reset_i | _017_);
  assign _000_[2] = _018_ & ~(_016_);
  assign _019_ = car_count[3] & _016_;
  assign _020_ = ~(car_count[3] | _016_);
  assign _021_ = ~(cnt_reset_i | _020_);
  assign _000_[3] = _021_ & ~(_019_);
  assign _022_ = car_count[4] & _019_;
  assign _023_ = ~(car_count[4] | _019_);
  assign _024_ = ~(cnt_reset_i | _023_);
  assign _000_[4] = _024_ & ~(_022_);
  assign _025_ = car_count[5] & _022_;
  assign _026_ = ~(car_count[5] | _022_);
  assign _027_ = ~(cnt_reset_i | _026_);
  assign _000_[5] = _027_ & ~(_025_);
  assign _028_ = ~(car_count[6] & _025_);
  assign _029_ = ~(car_count[6] | _025_);
  assign _030_ = ~(cnt_reset_i | _029_);
  assign _000_[6] = _028_ & _030_;
  assign _031_ = car_count[7] ^ _028_;
  assign _000_[7] = ~(cnt_reset_i | _031_);
  assign _032_ = timer[0] & ~(timer[1]);
  assign _033_ = cs[1] & ~(cs[2]);
  assign _034_ = _033_ & ~(cs[0]);
  assign _035_ = clear_i & _034_;
  assign _036_ = ~(_032_ & _035_);
  assign _037_ = ~(timer[0] & timer[1]);
  assign _038_ = cs[0] & ~(cs[2]);
  assign _039_ = ~(cs[1] & _038_);
  assign _040_ = _039_ | ~(_037_);
  assign _041_ = timer[0] | ~(timer[1]);
  assign _042_ = _038_ & ~(cs[1]);
  assign _043_ = ~(_041_ & _042_);
  assign _044_ = _040_ & _043_;
  assign _045_ = car_i & pay_ok_i;
  assign _046_ = ~(_007_ & _045_);
  assign _047_ = cs[2] | _046_;
  assign _048_ = _044_ & _047_;
  assign ns[0] = ~(_036_ & _048_);
  assign _049_ = _041_ | ~(_042_);
  assign _050_ = ~(_040_ & _049_);
  assign ns[1] = _034_ | _050_;
  assign _051_ = timer[0] | _008_;
  assign _052_ = _008_ & _039_;
  assign _053_ = _037_ & _051_;
  assign ns[2] = ~(_052_ | _053_);
  assign _054_ = timer[0] | _035_;
  assign _055_ = timer[0] & ~(cs[2]);
  assign _056_ = ~(clear_i & _055_);
  assign _057_ = ~(_007_ | _038_);
  assign _058_ = _056_ & _057_;
  assign _059_ = ~(_054_ & _058_);
  assign _060_ = timer[1] | ~(_042_);
  assign _061_ = _052_ & _060_;
  assign _062_ = timer[0] | _061_;
  assign next_timer[0] = ~(_059_ & _062_);
  assign _001_ = _040_ & _051_;
  assign _002_ = _006_ | _001_;
  assign _003_ = ~(_032_ & _042_);
  assign _004_ = ~(timer[1] & _058_);
  assign _005_ = _003_ & _004_;
  assign next_timer[1] = ~(_002_ & _005_);
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      cs[0] <= 0;
    else
      cs[0] <= ns[0];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      cs[1] <= 0;
    else
      cs[1] <= ns[1];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      cs[2] <= 0;
    else
      cs[2] <= ns[2];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      timer[0] <= 0;
    else
      timer[0] <= next_timer[0];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      timer[1] <= 0;
    else
      timer[1] <= next_timer[1];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[0] <= 0;
    else
      car_count[0] <= _000_[0];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[1] <= 0;
    else
      car_count[1] <= _000_[1];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[2] <= 0;
    else
      car_count[2] <= _000_[2];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[3] <= 0;
    else
      car_count[3] <= _000_[3];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[4] <= 0;
    else
      car_count[4] <= _000_[4];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[5] <= 0;
    else
      car_count[5] <= _000_[5];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[6] <= 0;
    else
      car_count[6] <= _000_[6];
  /* src = "top.v:39" */
  always @(posedge clk_i or negedge reset_i)
    if (!reset_i)
      car_count[7] <= 0;
    else
      car_count[7] <= _000_[7];
  assign L_green_o = 1'h0;
  assign L_red_o = 1'h1;
  assign L_yellow_o = 1'h0;
  assign car_count__o = car_count;
  assign gate_close_o = 1'h1;
  assign gate_open_o = 1'h0;
endmodule
